name: CI/CD with Spring Boot
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      S3ACCESKEY: ${{ secrets.S3ACCESKEY }}
      S3SECRETKEY: ${{ secrets.S3SECRETKEY }}
      OAUTH2CLIENTID: ${{ secrets.DB_PASSWORD }}
      OAUTH2CLIENTSECRETID: ${{ secrets.OAUTH2CLIENTSECRETID }}
      KEYDB:  ${{ secrets.KEYDB }}
      USERDB:  ${{ secrets.USERDB }}
      DB: ${{ secrets.DB}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 20
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '20'

      - name: Build with Maven
        run: mvn -B clean package -DskipTests --file pom.xml
      - name: Copy JAR to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "target/main-0.0.1-SNAPSHOT.jar"
          target: "/home/admin/java-files/main-0.0.1-SNAPSHOT.jar"

      - name: SSH into EC2 and start application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            echo ${{secrets.DB}}
            cd /home/admin/java-files/main-0.0.1-SNAPSHOT.jar/target
            sudo DB="$DB" USERDB="$USERDB" KEYDB="$KEYDB" S3ACCESKEY="$S3ACCESKEY" S3SECRETKEY="$S3SECRETKEY" OAUTH2CLIENTID="$OAUTH2CLIENTID" OAUTH2CLIENTSECRETID="$OAUTH2CLIENTSECRETID"  java -jar main-0.0.1-SNAPSHOT.jar

