name: CI/CD with Spring Boot

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 20
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '20'

      - name: Build with Maven
        run: mvn -B clean package -DskipTests --file pom.xml

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v2
        with:
          name: spring-boot-jar
          path: target/main-0.0.1-SNAPSHOT.jar

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Check if Docker image needs to be built
        id: check_changes
        run: |
          git fetch
          CHANGED_FILES=$(git diff HEAD^ --name-only)
          if [[ "$CHANGED_FILES" == *"Dockerfile"* || "$CHANGED_FILES" == *"docker-compose.yml"* ]]; then
            echo "::set-output name=build_image::true"
          else
            echo "::set-output name=build_image::false"
          fi
      - name: Remove existing JAR artifact
        run: rm -f /home/gitactions/contenedores/springBoot/main-0.0.1-SNAPSHOT.jar

      - name: Download JAR artifact
        uses: actions/download-artifact@v2
        with:
          name: spring-boot-jar
          path: /home/gitactions/contenedores/springBoot/


      - name: Build and update Docker image if necessary
        if: steps.check_changes.outputs.build_image == 'true'
        run: |
          cd /home/gitactions/contenedores/springBoot
          docker-compose down
          docker-compose build
          docker-compose up -d
        else
            echo "No changes in Dockerfile or docker-compose.yml. Skipping Docker image build."
        fi
