name: CI/CD with Spring Boot
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      S3ACCESKEY: ${{ secrets.S3ACCESKEY }}
      S3SECRETKEY: ${{ secrets.S3SECRETKEY }}
      OAUTH2CLIENTID: ${{ secrets.DB_PASSWORD }}
      OAUTH2CLIENTSECRETID: ${{ secrets.OAUTH2CLIENTSECRETID }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 20
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '20'

      - name: Build with Maven
        run: mvn -B clean package -DskipTests --file pom.xml
      - name: ver archivos
        run: |
            cd target;
            tree -c

