name: CI/CD with Spring Boot

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 20
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '20'

      - name: Build with Maven
        run: mvn -B clean package -DskipTests --file pom.xml

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v2
        with:
          name: spring-boot-jar
          path: target/main-0.0.1-SNAPSHOT.jar

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Download JAR artifact
        uses: actions/download-artifact@v2
        with:
          name: spring-boot-jar
          path: /home/gitactions/contenedores/springBoot/main-0.0.1-SNAPSHOT.jar

      - name: Build Docker image
        run: |
          cd /home/gitactions/contenedores/springBoot
          docker build -t springboot-app .

      - name: Run Docker Compose
        run: |
          cd /home/gitactions/contenedores/springBoot
          docker-compose up -d
